[package]
name = "chat-core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
tokio = {version = "*", features = ["full"]}
chrono = "0.4.43"

[lib]
crate-type = ["cdylib", "rlib"]