[package]
name = "chat-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
chat-core = {path = "../chat-core"}
ratatui = "0.30.0"
crossterm = "0.29.0"
tokio = {version = "1.49.0", features = ["full"]}

[[bin]]
name = "chat-tui"
path = "src/main.rs"